### ISSUE TITLE
API server does not expose openapi schema

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/sample-apiserver#12]
Kubectl depends on the models published through openapi to correctly validate and merge resources.  The sample API server does not publish the openapi.

**Comment by adohe** [comment]
This should be quite easy to do, we just need to add the OpenAPIConfig as follow:
```
serverConfig.OpenAPIConfig = genericapiserver.DefaultOpenAPIConfig(generatedopenapi.GetOpenAPIDefinitions, apiserver.Scheme)
serverConfig.OpenAPIConfig.Info.Title = "sample-apiserver"
serverConfig.SwaggerConfig = genericapiserver.DefaultSwaggerConfig()
serverConfig.EnableMetrics = true
```
The `GenericAPIServer.prepareRun` has already handle this setup. Oops... I have no idea how to generate OpenAPI spec.

**Comment by ayushpateria** [comment]
/remove-lifecycle stale

I'd like to work on this. As @adohe suggested, we can enable OpenAPI endpoint by setting the default OpenAPI configs for serverConfig. However, `generatedopenapi.GetOpenAPIDefinitions` needs to be generated prior to starting the server. I tried to find out how this is done for the Kubernetes API Server, and found that the definitions are generated as a part of the build process (Please refer [Makefile.generated_files#L490](https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile.generated_files#L490)). As of now we don't use a Makefile for `sample-apiserver`, so this approach is not possbile.

I see two ways to approach this:
- We generate the OpenAPI definitions and commit it in this repo. And we mention the steps to be followed to update the OpenAPI definitions in docs. This should be easy to do.

- Instead of using `go build .` to build `sample-apiserver` we build it through a Makefile. The make file can follow steps similar to `Makefile.generated_files`.

@sttts @nikhita Any suggestions on this?

**Comment by sttts** [comment]
@ayushpateria the code should go to https://github.com/kubernetes/sample-apiserver/blob/master/hack/update-codegen.sh. Please don't reinvent the `Makefile.generated_files` mechanism. It's far too complex.

**Comment by sttts** [comment]
@ayushpateria also please start with my PR https://github.com/kubernetes/kubernetes/pull/55472.

**Comment by sttts** [comment]
@ayushpateria looks like in https://github.com/kubernetes/kubernetes/pull/55472 only the wiring in the API server is missing. Can you add that (just use my code as a base and create another PR with the wiring).

**Comment by sttts** [comment]
To be fixed in https://github.com/kubernetes/kubernetes/pull/65440

**Comment by MikeSpreitzer** [comment]
/remove-lifecycle stale
This is _so_ evergreen!

**Comment by MikeSpreitzer** [comment]
I worked out an `openapi-gen` invocation by reverse-engineering Makefile.generated_files:
```
openapi-gen --logtostderr \
    -i k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1,k8s.io/sample-apiserver/pkg/apis/wardle/v1beta1 \
    -p k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/pkg/generated/openapi \
    -O zz_generated.openapi -r report
```

But I am confused.  Why is openapi-gen not part of what the regular code-generator does?

**Comment by MikeSpreitzer** [comment]
Thanks @adohe for the clue.  It now needs to look like the following.

```
	serverConfig := genericapiserver.NewRecommendedConfig(apiserver.Codecs)
	serverConfig.OpenAPIConfig = genericapiserver.DefaultOpenAPIConfig(generatedopenapi.GetOpenAPIDefinitions, openapinamer.NewDefinitionNamer(apiserver.Scheme))
```
