### ISSUE TITLE
How to add controller

### ISSUE THREAD

**Issue by Dimss** [kubernetes/sample-apiserver#41]
I'm trying to build K8s AA Server & integrated the controller logic. 
I've created the AA Server, it is up & running and I'm able to CRUD my resources. 
But I do not understand how should I add the K8s controller to make the "real" management of the resources. 
Can you please provide some example of how the K8s Controller can be integrated into Api Server. 
Many thanks

**Comment by Dimss** [comment]
I just found this [comment](https://github.com/kubernetes/sample-apiserver/issues/22#issuecomment-384560171)
So I added the informer (the generated code) and it is working as expected. 
And it's just I'm wonder, what is the right aporach can be here? 
```	informer := v1alpha12.NewClusterInformer(clientset, "", 1*time.Hour, nil)
	_, err = informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			log.Println("NEW OBJECT -----")
		},
		UpdateFunc: func(oldObj, newObj interface{}) {
			log.Println("UPDATE OBJECT -----")
		},
		DeleteFunc: func(obj interface{}) {
			log.Println("DELETE OBJECT -----")
		},
	})
	stopper := make(chan struct{})
	informer.Run(stopper)
```

**Comment by tarvitz** [comment]
@Dimss building a controller does not depend on API Aggregation or CRD, because this is an abstraction of how to deliver your data (custom kubernetes resoruces) to your client.

You require listers,informers, clientset to manipulate with objects and "reconcile" their state.

So basically, you might have CRD and AA running on different clusters with a the same version of controller.

Using https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen and modifying a bit these sources you might generate working CRD, register it and use it.

I'd recommend to inspect https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/cronjob as a controller code example.
